### PR TITLE
Support authorization url

### PR DESCRIPTION
**Pull request by qiwzhang**
If authentication fail with invalid token or expired token,  and if authorization url is set,  response with 302 with that url.

### CODE REVIEW

**Comment by lizan** [comment]
> If authentication fail with invalid token or expired token, and if authorization url is set, response with 302 with that url.

Any documentation describing this behavior? I couldn't find this in OpenAPI spec.

**Comment by qiwzhang** [comment]
Flex team requires us to behave such way to support their Auth.

**Comment by lizan** [comment]
From: [OpenAPI spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md) and [OpenID Connect spec](http://openid.net/specs/openid-connect-core-1_0.html#AuthorizationEndpoint) I feel the redirection should also include more request parameters extract from JWT, no?

The code itself LGTM.

**Comment by maroux** [comment]
Just ran into this "feature" which really sounds like a bug to me. Why should presence of `authorizationUrl` dictate 401 vs 302? Workaround is to set `authorizationUrl: ""` since it is required but can be empty.. At the very least, this should be documented [here](https://cloud.google.com/endpoints/docs/openapi/get-started-cloud-run).

**Pull request merged**
