### PR TITLE
Zero copy stream implement skip and count

### LINKED ISSUE #795: gRPC transcoder may truncate response data for unknown proto fields
If a proto field is unknown to ESP,  the transcoded response data maybe truncated.  This could happen when proto files used by ESP (the proto descriptor file used in "gcloud endpoints service deploy") and gRPC server are not in sync.

Example 1. a new field is recently added, but gRPC server is using updated proto, but ESP is using the old one. 
Example 2: a removed field, gRPC server is using old proto with that field, but ESP is using new proto.

This is because ESP did not implement Skip() [function](https://github.com/cloudendpoints/esp/blob/master/src/grpc/zero_copy_stream.h#L57).

Please see details [discussion](https://groups.google.com/d/msgid/google-cloud-endpoints/f5d681bc-6d2d-4eba-b02a-e9119d8b70d0%40googlegroups.com?utm_medium=email&utm_source=footer).

### PR DESCRIPTION
**Pull request by bnordli**
Fixes #795.

(Pair programming with @oyvindwe. He has the build environment, so he will verify compilation and tests later.)

### CODE REVIEW

**Comment by qiwzhang** [comment]
Test failure is due to code format

Files not formatted: src/grpc/zero_copy_stream_test.cc
Code style check failed.

whch is enforce by this script
script/robot-style

**Comment by qiwzhang** [comment]
@bnordli if you don't mind,  I can take over your change, and use a separate to submit it.

**Comment by bnordli** [comment]
That's fine with me, @qiwzhang, and probably much quicker too! Thanks :)

(I didn't have a build environment and just tried to follow the general formatting.)

We requested a CLA for my company today, but it seems like I committed with my personal email. Hopefully everything should be alright using nordli@exabel.com.

**Comment by bnordli** [comment]
No, the commit has the correct email. Let's check if my boss signed the CLA.

@googlebot I signed it!

**Pull request closed without merging**
