### PR TITLE
Integrate IAP JWT auto-verification for GAE Flex

### PR DESCRIPTION
**Pull request by kmbarry1**
This adds functionality that is part of larger system that allows IAP's signed JWTs to be verified automatically on App Engine Flex VMs.

### CODE REVIEW

**Comment by piyushnigam** [comment]
Wayne,

Is there anything we can do to speed up this review?

Thanks.

**Comment by qiwzhang** [comment]
Once it passes the presubmit test, I will merge it.

**Comment by piyushnigam** [comment]
Great! Thanks.

**Comment by qiwzhang** [comment]
We will build a lease with this change this week.

**Comment by liminw** [comment]
There is another PR "Adding ES256 for auth jwt validator" https://github.com/cloudendpoints/esp/pull/231 by Yu. Does that accomplish the same functionality as this one?

**Pull request merged**
