### PR TITLE
Added always_print_primitive_fields experimental option (#227)

### PR DESCRIPTION
**Pull request by rkdirect**
@lizan Here is the pull request as recommended in https://github.com/cloudendpoints/esp/issues/227

We are currently unable to verify the change as we have a few unknowns:
1. We do not have a means to produce a docker image, the documentation does not mention how to build this and it appears it requires a ".deb" package. I assume we are missing one or more build steps.
2. Does building the package and docker image require a specific operating system and/or version?
3. We are not aware of how to specify the "server config" or these "experimental" options when starting the service through the start_esp script.

### CODE REVIEW

**Comment by rkdirect** [comment]
I signed it!

**Comment by lizan** [comment]
@rkdirect Thanks for the PR, this is great, before I dive in to the code:
Can you make the PR against master? Only critical / security fixes go to release branches. New features like this should go to master.

re:
1. the Dockerfile is [here](https://github.com/cloudendpoints/esp/blob/master/docker/generic/Dockerfile), and the script we use to build docker image is [here](https://github.com/cloudendpoints/esp/blob/master/script/linux-build-docker). Sorry for the missing document.

2. Dockerfile contains the info :)

3. Sample server_config in proto text format is [here](https://github.com/cloudendpoints/endpoints-tools/blob/master/start_esp/server_config.pb.txt), if you use custom nginx.conf, you can load this as server_config, if not the template is [here](https://github.com/cloudendpoints/endpoints-tools/blob/master/start_esp/server-auto.conf.template), so add your experimental flags in it.

**Comment by rkdirect** [comment]
Thanks, I wasn't sure were to send the PR... You can close 294 and review
https://github.com/cloudendpoints/esp/pull/295

**Comment by lizan** [comment]
Closing in favor of #295

**Pull request closed without merging**
