### PR TITLE
Add the start_esp tests

### PR DESCRIPTION
**Pull request by lei-tang**
Per the request from https://github.com/cloudendpoints/endpoints-tools/issues/61,
1. Add 22 tests for start_esp to check that the ESP nginx configuration file generated are as expected.
2. Add 9 tests for start_esp to check that the ESP server configuration file generated are as expected.

This PR depends on https://github.com/cloudendpoints/endpoints-tools/pull/66, so it should be committed after https://github.com/cloudendpoints/endpoints-tools/pull/66 is merged in the endpoints-tools repo and the endpoints-tool repo SHA is updated.

### CODE REVIEW

**Comment by qiwzhang** [comment]
Thanks.   I think the test should be in esp_tools repo:  if there are some changes, many golden files need to be updated. Otherwise the test will fail.   We want the author making the change to fix the test too.

But our Jenkins presubmit tests only run for esp repo.   We don't have auto tests for esp_tools repo.

Not sure how easy to setup Jenkins in esp_tools repo.

Another option is to move files in start_esp folder into esp repo.  Then, we can add test here.

**Comment by lei-tang** [comment]
I am leaning towards the option of moving files in start_esp folder into esp repo because:
1. with this option, start_esp.py and its related tests can be edited and run in ESP repo without updating and syncing to the SHA of endpoints-tools.
2. with this option, ESP repo no longer needs to copy start_esp.py and nginx conf template from endpoints-tools repo. Though these files are stored in the endpoints-tools repo, they are only used in the ESP repo. So it is natural to move them into the ESP repo. Plus, the developers will be able to work on the ESP repository only instead of two repositories (ESP and endpoints-tools).

**Comment by qiwzhang** [comment]
Yes,  SGTM.   Let us create a PR to move the files first,  then this PR.

**Comment by lei-tang** [comment]
The PR https://github.com/cloudendpoints/esp/pull/420 and https://github.com/cloudendpoints/endpoints-tools/pull/69 are created to move start_esp from the endpoints-tools repository to the ESP repository.

**Comment by lei-tang** [comment]
@qiwzhang 
This PR has been rebased to the latest moved start_esp code (Move start_esp from the endpoints-tools repository to the ESP repository https://github.com/cloudendpoints/esp/commit/29452e3415190305ceadfdf281a12530a36c0510). 

It has passed the presubmit test and e2e tests: https://endpoints-jenkins.appspot.com/job/esp/job/presubmit/1110/,  https://endpoints-jenkins.appspot.com/job/jenkins-testing/job/pr-e2e/119/

Please review it again.

**Pull request merged**
