### PR TITLE
add additonal bindings support

### PR DESCRIPTION
**Pull request by Rajczyk**
1. Added support for additional_bindings
2. Cleaned up some of the logic to make it easier for adding additional_bindings

### CODE REVIEW

**Comment by Rajczyk** [comment]
I signed it!

**Comment by qiwzhang** [comment]
@Rajczyk Thanks for the contribution.  A couple comment about the PR
1) please run this script to format hour code: https://github.com/istio/proxy/blob/master/script/check-style
2) add some unit-tests in config_test.cc
3) add a "t" test (end to end test), similar to other t tests in folder src/nignx/t.  There are some grpc tests too.

**Comment by Rajczyk** [comment]
I'm not sure which is the best place to add my end to end test. The grpc-test (grpc-test.proto) has no proto bindings and the transcoding test (bookstore-api.yaml) uses only yaml bindings. 

Should I add additional_bindings to bookstore-api.yaml? and create a new /transcoding/grpc test?

[esp/test/grpc/grpc-test.proto](https://github.com/cloudendpoints/esp/blob/1775d95306a21ae43d71ec20f633600074ab4119/test/grpc/grpc-test.proto)
[esp/test/transcoding/bookstore-api.yaml](https://github.com/cloudendpoints/esp/blob/1775d95306a21ae43d71ec20f633600074ab4119/test/transcoding/bookstore-api.yaml)

**Comment by qiwzhang** [comment]
build esp/presubmit

**Comment by qiwzhang** [comment]
Ping,  do you still want to get this in?

**Comment by qiwzhang** [comment]
As expected, presubmit test failed for code format error:

Checking coding styles.
Files not formatted: src/api_manager/config.cc src/api_manager/config.h
Code style check failed.

You have to install clang 3.8.0 to format the code as

clang/clang-3.8.0/bin/clang-format -style=google -i

**Pull request closed without merging**
